### ISSUE TITLE
Does it support right arrow ?

### ISSUE THREAD

**Issue by Folyd** [xizzhu/simple-tool-tip#1]
I look into the source code,it seem like not support right arrow yet.

**Comment by xizzhu** [comment]
No, not yet. I'll check that soon.

**Comment by Folyd** [comment]
May be we add a `gravity` property for `ToolTipView`, i will try my method,if that work, if will make a pull request. :smile:

**Comment by Folyd** [comment]
Another question, there is a big limitation,the parent view must be `FrameLayout` or `RelativeLayout`?

**Comment by Folyd** [comment]
Why not use `PopupWindow` to implement this?I think this cloud be better. :smiley:

**Comment by xizzhu** [comment]
Closed as https://github.com/xizzhu/simple-tool-tip/pull/2 is merged.
