### ISSUE TITLE
setOnToolTipClickedListener to build another tooltip isn't working

### ISSUE THREAD

**Issue by marios-codes** [xizzhu/simple-tool-tip#4]
Below is a code snippet I use trying to build a second tooltip when someone clicks the first tooltip. The result is that the first tooltip closes, but the second one isn't showing. Is what I am trying to do supported by the library or am I doing something wrong. Thanks!!

```
//test tooltip for fab
final FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);

    final float scale = getApplicationContext().getResources().getDisplayMetrics().density;
    final int textSizePixels = (int) (16 * scale + 0.5f);
    final int tooltipPadding = (int) (8 * scale + 0.5f);

ToolTip plusOneToolTip = new ToolTip.Builder()
            .withText("Some tooltip text")
            .withTextSize(textSizePixels)
            .withPadding(tooltipPadding, tooltipPadding, tooltipPadding, tooltipPadding)
            .withCornerRadius(15)
            .withBackgroundColor(ContextCompat.getColor(MainActivity.this, R.color.colorPrimary))
            .build();
    ToolTipView plusOneTooltipView = new ToolTipView.Builder(MainActivity.this)
            .withAnchor(fab)
            .withToolTip(plusOneToolTip)
            .withGravity(Gravity.TOP)
            .build();
    plusOneTooltipView.show();
    plusOneTooltipView.setOnToolTipClickedListener(new ToolTipView.OnToolTipClickedListener() {
        @Override
        public void onToolTipClicked(ToolTipView toolTipView) {
            Button goToSleepButton = (Button) findViewById(R.id.sleepButton);

            final float scale = getApplicationContext().getResources().getDisplayMetrics().density;
            int textSizePixels = (int) (16 * scale + 0.5f);
            int tooltipPadding = (int) (8 * scale + 0.5f);

            ToolTip sleepToolTip = new ToolTip.Builder()
                    .withText("Tap this when your day ends")
                    .withTextSize(textSizePixels)
                    .withPadding(tooltipPadding, tooltipPadding, tooltipPadding, tooltipPadding)
                    .withCornerRadius(15)
                    .withBackgroundColor(ContextCompat.getColor(MainActivity.this, R.color.colorPrimary))
                    .build();
            ToolTipView sleepTooltipView = new ToolTipView.Builder(MainActivity.this)
                    .withAnchor(goToSleepButton)
                    .withToolTip(sleepToolTip)
                    .withGravity(Gravity.TOP)
                    .build();
            sleepTooltipView.show();
        }
    });
```

**Comment by xizzhu** [comment]
Hi, the `setOnToolTipClickedListener()` only keep a `WeakReference` to the listener, so it's GC'ed. I'll update the doc.

**Comment by marios-codes** [comment]
Thank you very much for the reply. Because I didn't understand it very well, is it possible to show another tooltips, after clicking the first one, or it is not implemented yet? Thank you for your time!

**Comment by xizzhu** [comment]
OK, now it should work with 0.4.0, and no need to change your code. It no longer keeps a `WeakReference` but now a strong reference. I actually don't know why I decided the other way...

**Comment by marios-codes** [comment]
Thank you very much! I will try it later today!

**Comment by marios-codes** [comment]
Hi there, I updated the library to 0.4.0, but the problem still persists with the above code snippet. I tried to clean the project and rebuild it, but no luck. Have you tested it, and it works on your behalf?? Thank you

**Comment by xizzhu** [comment]
Yes, it works for me. Can you check if the callback is called? Is your `goToSleepButton` visible when the callback is called?

**Comment by marios-codes** [comment]
I debugged the above code and the callback is called, also the `goToSleepButton`     is visible! However after the `sleepTooltipView.show();` is called, the debugger goes to a `Looper.java` class. Could you please share your working sample code to compare it with mine??

**Comment by xizzhu** [comment]
I'm using https://github.com/xizzhu/simple-tool-tip/blob/master/app/src/main/java/com/github/xizzhu/simpletooltip/sample/MainActivity.java#L123, and simply calling `showToolTipView()` in the callback and that works for me.

Can you share some minimum code to reproduce this, including the layout file?

**Comment by marios-codes** [comment]
For the shake of simplicity I tried to delete all the ununecessary code. So this is the code I am using for the tooltips.

[activity_main.xml](http://pastebin.com/4RYffmWS)
[MainActivity.java](http://pastebin.com/AGCMRt4w)

If I can provide you with more info, I would be happy to help!!

**Comment by xizzhu** [comment]
As of now, when you use `withAnchor()`, it's expecting anchor's parent view to be a `FrameLayout` or a `RelativeLayout`. As a work around for now, please read the doc and use `withParent()`.

I'm working on a proper solution.

**Comment by marios-codes** [comment]
Thank you very much for your time and efforts. I will try your proposal.
Please answer to this thread if you find a solution!! Cheers!!
