### ISSUE TITLE
Library doesn't allow to use complex view hierarchy

### ISSUE THREAD

**Issue by gwheet** [xizzhu/simple-tool-tip#5]
Let say I have following view hierarchy

ScrollView
--FrameLayout <<-- view holder
----LinearLayout
------Button1
------Button2
------LinearLayout << - direct parent view
--------Button3
--------Button4
------Button5
------Button6

just like in sample application but we want to include 3,4 buttons inside additional LinearLayout.
It will lead to issues with showing tooltip because it uses position relative to parent view (direct parent) rather then view holder.

I did simple modification of onPreDraw() method that perform search of parent view and calculate correct relative coordinates.

```
@Override
public boolean onPreDraw() {
    getViewTreeObserver().removeOnPreDrawListener(this);

    View parent = (View) getParent();
    int parentWidth = parent.getWidth();
    int parentHeight = parent.getHeight();

    // calculate coordinates relative to parent view
    int relativeTop = 0;
    int relativeLeft = 0;

    View currentParent = (View) anchorView.getParent();
    while (currentParent != parent) {
        if (!(currentParent.getParent() instanceof View)) {
            throw new IllegalArgumentException(
                    "Anchor view must be child of specified parent view.");
        }
        View newParent = (View) currentParent.getParent();
        relativeTop += currentParent.getTop();
        relativeLeft += currentParent.getLeft();
        currentParent = newParent;
    }

    int anchorTop = anchorView.getTop() + relativeTop;
    int anchorLeft = anchorView.getLeft() + relativeLeft;
    int anchorWidth = anchorView.getWidth();
    int anchorHeight = anchorView.getHeight();

    // rest code
   ...
```

}

**Comment by xizzhu** [comment]
Supported with commit 2e756b8fb022caebd97268d536bcddcf601848ec and will be released soon.
