### ISSUE TITLE
Does it work with Toolbar items?

### ISSUE THREAD

**Issue by ParitoshBh** [xizzhu/simple-tool-tip#6]
This is more of a question than an issue, so you can close it without even answering!

Anyhow, in documentation I couldn't find if this library works for showing tooltips for toolbar items.

**Comment by xizzhu** [comment]
No, it doesn't support that. I can check how to support that soon.

**Comment by ParitoshBh** [comment]
I did try that before posting here by finding out view for toolbar item using findViewbyId(R.id.menu_item). Interestingly it did work but only once. After that I kept on getting some error pointing to calculation points (from this library).

It could be that for that one time occurrence the onCreateOptionsMenu was called before tooltip was setup.

**Comment by xizzhu** [comment]
Supported by commit 2e756b8fb022caebd97268d536bcddcf601848ec, and will be released soon.
